# Generated by Django 3.1.7 on 2023-03-08 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity_users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadEmployeeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_name', models.FileField(upload_to='')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_entityusers', to='entity_users.entityusers')),
            ],
            options={
                'verbose_name': 'UploadEmployeeFile',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=225)),
                ('middle_name', models.CharField(blank=True, max_length=225, null=True)),
                ('last_name', models.CharField(max_length=225)),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('email', models.CharField(max_length=225, unique=True)),
                ('temp_password', models.CharField(blank=True, max_length=225, null=True)),
                ('password', models.CharField(blank=True, max_length=225, null=True)),
                ('department', models.CharField(blank=True, max_length=225, null=True)),
                ('job_title', models.CharField(blank=True, max_length=225, null=True)),
                ('region', models.CharField(blank=True, max_length=225, null=True)),
                ('language', models.CharField(blank=True, max_length=225, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_entityusers', to='entity_users.entityusers')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
