# Generated by Django 3.1.7 on 2023-03-08 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityUsers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=225)),
                ('middle_name', models.CharField(blank=True, max_length=225, null=True)),
                ('last_name', models.CharField(blank=True, max_length=225, null=True)),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('email', models.CharField(max_length=225, unique=True)),
                ('temp_password', models.CharField(blank=True, max_length=225)),
                ('password', models.CharField(blank=True, max_length=225, null=True)),
                ('department', models.CharField(blank=True, max_length=225, null=True)),
                ('job_title', models.CharField(blank=True, max_length=225, null=True)),
                ('region', models.CharField(blank=True, max_length=225, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_role', models.CharField(choices=[('Company Admin', 'Company Admin'), ('Company Stuff', 'Company Stuff')], default='Company Admin', max_length=50)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entityusers_company', to='company.company')),
                ('parent_entityuser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_entityusers', to='entity_users.entityusers')),
            ],
            options={
                'verbose_name': 'Company Admin',
                'verbose_name_plural': 'Company Admin',
            },
        ),
    ]
